### ISSUE TITLE
tinykeys_1.default is not a function

### ISSUE THREAD

**Issue by screendriver** [jamiebuilds/tinykeys#138]
With the latest version `v1.3.0` I'm getting

```
TypeError: (0 , tinykeys_1.default) is not a function
```

in my webpack build and also in my unit tests that are running with [ts-node/register/transpile-only](https://github.com/TypeStrong/ts-node#options). My import looks as in the previous versions

```ts
import tinykeys from 'tinykeys';
```

and I'm using `TypeScript` with `esModuleInterop` enabled.

**Comment by chenrui333** [comment]
Run into the same issue when upgrading from 1.2.0 to 1.3.0. Also with `esModuleInterop` enabled.

**Comment by erictheswift** [comment]
@jamiebuilds Hey! Thanks for the effort.

Can you please release this change? [1.4.0](https://github.com/jamiebuilds/tinykeys/releases/tag/v1.4.0) is latest published version dated before this merge
