### PR TITLE
Use only named export

### LINKED ISSUE #138: tinykeys_1.default is not a function
With the latest version `v1.3.0` I'm getting

```
TypeError: (0 , tinykeys_1.default) is not a function
```

in my webpack build and also in my unit tests that are running with [ts-node/register/transpile-only](https://github.com/TypeStrong/ts-node#options). My import looks as in the previous versions

```ts
import tinykeys from 'tinykeys';
```

and I'm using `TypeScript` with `esModuleInterop` enabled.

### PR DESCRIPTION
**Pull request by nus3**
resolve #138 

rollup.js, on which Microbundle depends, is bad practice to mix default and named exports in same module.
https://rollupjs.org/guide/en/#default-export

So I changed it to use only named exports.

### CODE REVIEW

File: src/tinykeys.ts [hunk 1]
```diff
@@ -214,7 +214,7 @@ export function createKeybindingsHandler(
  * })
  * ```
  */
-export default function keybindings(
+function keybindings(
```
Comment (jamiebuilds) [inline src/tinykeys.ts:217]: want to just name this like:

```ts
export function tinykeys(...) {...}
```

Comment (nus3) [reply src/tinykeys.ts]: Thanks for review!

Fixed from this commit.
https://github.com/jamiebuilds/tinykeys/pull/161/commits/629b037a271ed4de160ae232825c9ee335b009e4

**Comment by erictheswift** [comment]
@jamiebuilds Hey! Thanks for the effort.

Can you please release this change? [1.4.0](https://github.com/jamiebuilds/tinykeys/releases/tag/v1.4.0) is latest published version dated before this merge
